# Numpy, la brique de base de la data science

Lino Galiana  
2025-10-06

<div class="badge-container"><div class="badge-text">Pour essayer les exemples présents dans ce tutoriel :</div><a href="https://github.com/linogaliana/python-datascientist-notebooks/blob/main/notebooks/manipulation/01_numpy.ipynb" target="_blank" rel="noopener"><img src="https://img.shields.io/static/v1?logo=github&label=&message=View%20on%20GitHub&color=181717" alt="View on GitHub"></a>
<a href="https://datalab.sspcloud.fr/launcher/ide/vscode-python?autoLaunch=true&name=«01_numpy»&init.personalInit=«https%3A%2F%2Fraw.githubusercontent.com%2Flinogaliana%2Fpython-datascientist%2Fmain%2Fsspcloud%2Finit-vscode.sh»&init.personalInitArgs=«manipulation%2001_numpy%20correction»" target="_blank" rel="noopener"><img src="https://custom-icon-badges.demolab.com/badge/SSP%20Cloud-Lancer_avec_VSCode-blue?logo=vsc&logoColor=white" alt="Onyxia"></a>
<a href="https://datalab.sspcloud.fr/launcher/ide/jupyter-python?autoLaunch=true&name=«01_numpy»&init.personalInit=«https%3A%2F%2Fraw.githubusercontent.com%2Flinogaliana%2Fpython-datascientist%2Fmain%2Fsspcloud%2Finit-jupyter.sh»&init.personalInitArgs=«manipulation%2001_numpy%20correction»" target="_blank" rel="noopener"><img src="https://img.shields.io/badge/SSP%20Cloud-Lancer_avec_Jupyter-orange?logo=Jupyter&logoColor=orange" alt="Onyxia"></a>
<a href="https://colab.research.google.com/github/linogaliana/python-datascientist-notebooks-colab//blob/main//notebooks/manipulation/01_numpy.ipynb" target="_blank" rel="noopener"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a><br></div>

> **Note**
>
> Ceci est la version française 🇫🇷 de ce chapitre, pour voir la version anglaise allez <a href="/home/runner/work/python-datascientist/python-datascientist/en/content/manipulation/01_numpy.qmd">ici</a>.

# 1. Introduction

Ce chapitre constitue une introduction à *Numpy* pour
s’assurer que les bases du calcul vectoriel avec `Python`
soient maîtrisées. La première partie du chapitre
présente des petits exercices pour pratiquer quelques fonctions basiques de `Numpy`. La fin du chapitre présente
des exercices pratiques d’utilisation de `Numpy` plus approfondis.

Il est recommandé de régulièrement se référer à
la [*cheatsheet numpy*](https://www.datacamp.com/community/blog/python-numpy-cheat-sheet) et à la
[doc officielle](https://numpy.org/doc/stable/) en cas de doute
sur une fonction.

Dans ce chapitre, on ne dérogera pas à la convention qui s’est imposée
d’importer `Numpy` de la
manière suivante :

In [ ]:
import numpy as np

Nous allons également fixer la racine du générateur aléatoire de nombres
afin d’avoir des résultats reproductibles :

In [ ]:
import numpy as np
rng = np.random.default_rng(seed=12345)

> **Caution**
>
> Historiquement, la génération de nombres aléatoires se faisait pas le biais du package `numpy.random`. Néanmoins, les auteurs de `Numpy` [recommandent maintenant](https://numpy.org/doc/stable/reference/random/index.html) d’utiliser plutôt des générateurs pour cela. Les exemples de ce tutoriel adoptent donc cette pratique.

# 2. Le concept d’*array*

Dans le monde de la science des données, comme cela sera évoqué
plus en profondeur dans les prochains chapitres,
l’objet central est le tableau à deux dimensions de données.
La première correspond aux lignes et la seconde aux colonnes.
Si on ne se préoccupe que d’une dimension, on se rapporte
à une variable (une colonne) de notre tableau de données.
Il est donc naturel de faire le lien entre les
tableaux de données et l’objet mathématique
que sont les matrices et les vecteurs.

`NumPy` (`Numerical Python`) est la brique de base
pour traiter des listes numériques ou des chaines
de textes comme des matrices.
`NumPy` intervient pour proposer
ce type d’objets, et
les opérations standardisées associées qui n’existent
pas dans le langage `Python` de base.

L’objet central de `NumPy` est
l’**`array`** qui est un tableau de données multidimensionnel.
L’array `Numpy` peut être unidimensionnel et s’apparenter à un
vecteur (`1d-array`),
bidimensionnel et ainsi s’apparenter à une matrice (`2d-array`) ou,
de manière plus générale,
prendre la forme d’un objet
multidimensionnel (`Nd-array`), sorte de tableau emboîté.

Les tableaux simples (uni ou bi-dimensionnels) sont faciles à se représenter
et représentent la majorité des besoins liés à `Numpy`.
Nous découvrirons lors du chapitre suivant, sur `Pandas`, qu’en pratique
on manipule rarement directement `Numpy` qui est une librairie
bas niveau.
Un *DataFrame* `Pandas` sera construit à partir d’une collection
d’array uni-dimensionnels (les variables de la table), ce qui permettra d’effectuer des opérations cohérentes
(et optimisées) avec le type de la variable.
Avoir quelques notions `Numpy` est utile pour comprendre
la logique de manipulation vectorielle
rendant les traitements sur des données plus lisibles,
plus efficaces et plus fiables.

Par rapport à une liste,

-   un *array* ne peut contenir qu’un type de données (`integer`, `string`, etc.),
    contrairement à une liste.
-   les opérations implémentées par `Numpy` seront plus efficaces et demanderont moins
    de mémoire

Les données géographiques constitueront une construction un peu plus complexe qu’un `DataFrame` traditionnel.
La dimension géographique prend la forme d’un tableau plus profond, au moins bidimensionnel
(coordonnées d’un point). Néanmoins, les librairies de manipulation
de données géographiques permettront de ne pas se préoccuper de
cette complexité accrue.

## 2.1 Créer un array

On peut créer un *array* de plusieurs manières. Pour créer un *array* à partir d’une liste,
il suffit d’utiliser la méthode `array`:

In [ ]:
np.array([1,2,5])

array([1, 2, 5])

Il est possible d’ajouter un argument `dtype` pour contraindre le type du *array* :

In [ ]:
np.array([["a","z","e"],["r","t"],["y"]], dtype="object")

array([list(['a', 'z', 'e']), list(['r', 't']), list(['y'])], dtype=object)

Il existe aussi des méthodes pratiques pour créer des array:

-   séquences logiques : `np.arange` (suite) ou `np.linspace` (interpolation linéaire entre deux bornes) ;
-   séquences ordonnées : *array* rempli de zéros, de 1 ou d’un nombre désiré : `np.zeros`, `np.ones` ou `np.full` ;
-   séquences aléatoires : fonctions de génération de nombres aléatoires : `rng.uniform`, `rng.normal`, etc. où `rng` est un générateur de nombre aléatoires ;  
-   tableau sous forme de matrice identité : `np.eye`.

Ceci donne ainsi, pour les séquences logiques:

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Pour un *array* initialisé à 0:

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

ou initialisé à 1:

In [ ]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

ou encore initialisé à 3.14:

In [ ]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Enfin, pour créer la matrice $I_3$:

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

> **Exercice 1**
>
> Générer:
>
> -   $X$ une variable aléatoire, 1000 répétitions d’une loi $U(0,1)$
> -   $Y$ une variable aléatoire, 1000 répétitions d’une loi normale de moyenne nulle et de variance égale à 2
> -   Vérifier la variance de $Y$ avec `np.var`

# 3. Indexation et *slicing*

## 3.1 Logique dans le cas d’un array unidimensionnel

La structure la plus simple est l’*array* unidimensionnel:

In [ ]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]

L’indexation est dans ce cas similaire à celle d’une liste:

-   le premier élément est 0
-   le énième élément est accessible à la position $n-1$

La logique d’accès aux éléments est ainsi la suivante :

``` python
x[start:stop:step]
```

Avec un *array* unidimensionnel, l’opération de *slicing* (garder une coupe du *array*) est très simple.
Par exemple, pour garder les *K* premiers éléments d’un *array*, on fera:

``` python
x[:K]
```

En l’occurrence, on sélectionne le K$^{eme}$ élément en utilisant

``` python
x[K-1]
```

Pour sélectionner uniquement un élément, on fera ainsi:

In [ ]:
x = np.arange(10)
x[2]

np.int64(2)

Les syntaxes qui permettent de sélectionner des indices particuliers d’une liste fonctionnent également
avec les *arrays*.

> **Exercice 2**
>
> Prenez `x = np.arange(10)` et…
>
> -   Sélectionner les éléments 0, 3, 5 de `x`
> -   Sélectionner les éléments pairs
> -   Sélectionner tous les éléments sauf le premier
> -   Sélectionner les 5 premiers éléments

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

La logique se généralise pour les *array* multidimensionnels. L’indexation se fait alors à plusieurs niveaux. Prenons par exemple un array à 2 dimensions (une matrice en quelques sortes):

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

Si on veut sélectionner la 2e ligne, 3e colonne (l’élément de valeur 6), on fait

In [ ]:
x[1, 2]

np.int32(6)

Maintenant, pour sélectionner une colonne complète (par exemple la 2e), on peut utiliser le 2e index pour spécifier celle-ci (index 1 en Python puisque l’indexation part de 0) puis `:` sur la première dimension (version raccourcie de `0:N`) pour ne pas discriminer selon cette dimension:

In [ ]:
x[:,1]

array([2, 5], dtype=int32)

Le principe se généralise, mais se complexifie, pour des *array* imbriqués. Heureusement, ce sont des objets qu’on manipule assez rarement directement, la plupart de nos données numériques étant des tableaux plats (une valeur - l’observation - est le croisement d’une ligne - l’individu - et d’une colonne - la variable).

## 3.2 Sur la performance

Un élément déterminant dans la performance de `Numpy` par rapport aux listes,
lorsqu’il est question de
*slicing* est qu’un array ne renvoie pas une
copie de l’élément en question (copie qui coûte de la mémoire et du temps)
mais simplement une vue de celui-ci.

Lorsqu’il est nécessaire d’effectuer une copie,
par exemple pour ne pas altérer l’*array* sous-jacent, on peut
utiliser la méthode `copy`:

``` python
x_sub_copy = x[:2, :2].copy()
```

## 3.3 Filtres logiques

Il est également possible, et plus pratique, de sélectionner des données à partir de conditions logiques
(opération qu’on appelle un ***boolean mask***).
Cette fonctionalité servira principalement à
effectuer des opérations de filtre sur les données.

Pour des opérations de comparaison simples, les comparateurs logiques peuvent être suffisants.
Ces comparaisons fonctionnent aussi sur les tableaux multidimensionnels grâce au
*broadcasting* sur lequel nous reviendrons :

In [ ]:
x = np.arange(10)
x2 = np.array([[-1,1,-2],[-3,2,0]])
print(x)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[[-1  1 -2]
 [-3  2  0]]

In [ ]:
x==2
x2<0

array([[ True, False,  True],
       [ True, False, False]])

Pour sélectionner les observations relatives à la condition logique,
il suffit d’utiliser la logique de *slicing* de `numpy` qui fonctionne avec les conditions logiques

> **Exercice 3**
>
> Soit
>
> ``` python
> x = np.random.normal(size=10000)
> ```
>
> 1.  Ne conserver que les valeurs dont la valeur absolue est supérieure à 1.96
> 2.  Compter le nombre de valeurs supérieures à 1.96 en valeur absolue et leur proportion dans l’ensemble
> 3.  Sommer les valeurs absolues de toutes les observations supérieures (en valeur absolue) à 1.96
>     et rapportez les à la somme des valeurs de `x` (en valeur absolue)

Lorsque c’est possible, il est recommandé d’utiliser les fonctions logiques de `numpy` (optimisées et
qui gèrent bien la dimension).
Parmi elles, on peut retrouver:

-   `count_nonzero` ;
-   `isnan` ;
-   `any` ou `all`, notamment avec l’argument `axis` ;
-   `np.array_equal` pour vérifier, élément par élément, l’égalité.

Soient `x` un *array* multidimensionnel et `y` un *array* unidimensionnel présentant une valeur manquante.

In [ ]:
# Assuming rng has been created beforehand
x = rng.normal(0, size=(3, 4))
y = np.array([np.nan, 0, 1])

> **Exercice 4**
>
> 1.  Utiliser `count_nonzero` sur `y`
> 2.  Utiliser `isnan` sur `y` et compter le nombre de valeurs non NaN
> 3.  Vérifier que `x` comporte au moins une valeur positive dans son ensemble, en parcourant les lignes puis les colonnes.
>
> <details>
>
> <summary>
>
> Aide
>
> </summary>
>
> Jetez un oeil au paramètre `axis` en vous documentant sur internet. Par exemple [ici](https://www.sharpsightlabs.com/blog/numpy-axes-explained/).
>
> </details>

# 4. Manipuler un *array*

## 4.1 Fonctions de manipulation

`Numpy` propose des méthodes ou des fonctions standardisées pour
modifier un array, voici un tableau en présentant quelques-unes:

| Opération | Implémentation |
|------------------------------|------------------------------------------|
| Aplatir un array | `x.flatten()` (méthode) |
| Transposer un array | `x.T` (méthode) ou `np.transpose(x)` (fonction) |
| Ajouter des éléments à la fin | `np.append(x, [1,2])` |
| Ajouter des éléments à un endroit donné (aux positions 1 et 2) | `np.insert(x, [1,2], 3)` |
| Supprimer des éléments (aux positions 0 et 3) | `np.delete(x, [0,3])` |

Pour combiner des array, on peut utiliser, selon les cas,
les fonctions `np.concatenate`, `np.vstack` ou la méthode `.r_` (concaténation *rowwise*).
`np.hstack` ou la méthode `.column_stack` ou `.c_` (concaténation *column-wise*)

In [ ]:
x = rng.normal(size = 10)

Pour ordonner un array, on utilise `np.sort`

In [ ]:
x = np.array([7, 2, 3, 1, 6, 5, 4])

np.sort(x)

array([1, 2, 3, 4, 5, 6, 7])

Si on désire faire un ré-ordonnement partiel pour trouver les *k* valeurs les plus petites d’un `array` sans les ordonner, on utilise `partition`:

In [ ]:
np.partition(x, 3)

array([1, 2, 3, 4, 5, 6, 7])

## 4.2 Statistiques sur un *array*

Pour les statistiques descriptives classiques,
`Numpy` propose un certain nombre de fonctions déjà implémentées,
qui peuvent être combinées avec l’argument `axis`

In [ ]:
x = rng.normal(0, size=(3, 4))

> **Exercice 5**
>
> 1.  Faire la somme de tous les éléments d’un `array`, des éléments en ligne et des éléments en colonne. Vérifier
>     la cohérence.
> 2.  Ecrire une fonction `statdesc` pour renvoyer les valeurs suivantes : moyenne, médiane, écart-type, minimum et maximum.
>     L’appliquer sur `x` en jouant avec l’argument *axis*

# 5. *Broadcasting*

Le *broadcasting* désigne un ensemble de règles permettant
d’appliquer des opérations sur des tableaux de dimensions différentes. En pratique,
cela consiste généralement à appliquer une seule opération à l’ensemble des membres d’un tableau `numpy`.

La différence peut être comprise à partir de l’exemple suivant. Le *broadcasting* permet
de transformer le scalaire `5` en *array* de dimension 3:

In [ ]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

a + b
a + 5

array([5, 6, 7])

Le *broadcasting* peut être très pratique pour effectuer de manière efficace des opérations sur des données à
la structure complexe. Pour plus de détails, se rendre
[ici](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html) ou [ici](https://stackoverflow.com/questions/47435526/what-is-the-meaning-of-axis-1-in-keras-argmax).

## 5.1 Une application: programmer ses propres k-nearest neighbors

> **Exercice 6 (un peu plus corsé)**
>
> 1.  Créer `X` un tableau à deux dimensions (i.e. une matrice) comportant 10 lignes
>     et 2 colonnes. Les nombres dans le tableau sont aléatoires.
> 2.  Importer le module `matplotlib.pyplot` sous le nom `plt`. Utiliser
>     `plt.scatter` pour représenter les données sous forme de nuage de points.
> 3.  Constuire une matrice 10x10 stockant, à l’élément $(i,j)$, la distance euclidienne entre les points $X[i,]$ et $X[j,]$. Pour cela, il va falloir jouer avec les dimensions en créant des tableaux emboîtés à partir par des appels à `np.newaxis` :
>     1.  En premier lieu, utiliser `X1 = X[:, np.newaxis, :]` pour transformer la matrice en tableau emboîté. Vérifier les dimensions
>     2.  Créer `X2` de dimension `(1, 10, 2)` à partir de la même logique
>     3.  En déduire, pour chaque point, la distance avec les autres points pour chaque coordonnées. Elever celle-ci au carré
>     4.  A ce stade, vous devriez avoir un tableau de dimension `(10, 10, 2)`. La réduction à une matrice s’obtient en sommant sur le dernier axe. Regarder dans l’aide de `np.sum` comme effectuer une somme sur le dernier axe.
>     5.  Enfin, appliquer la racine carrée pour obtenir une distance euclidienne en bonne et due forme.
> 4.  Vérifier que les termes diagonaux sont bien nuls (distance d’un point à lui-même…)
> 5.  Il s’agit maintenant de classer, pour chaque point, les points dont les valeurs sont les plus similaires. Utiliser `np.argsort` pour obtenir, pour chaque ligne, le classement des points les plus proches
> 6.  On va s’intéresser aux k-plus proches voisins. Pour le moment, fixons k=2. Utiliser `argpartition` pour réordonner chaque ligne de manière à avoir les 2 plus proches voisins de chaque point d’abord et le reste de la ligne ensuite
> 7.  Utiliser le morceau de code ci-dessous

<details><summary>Un indice pour représenter graphiquement les plus proches voisins</summary>

``` python
plt.scatter(X[:, 0], X[:, 1], s=100)

# draw lines from each point to its two nearest neighbors
K = 2

for i in range(X.shape[0]):
    for j in nearest_partition[i, :K+1]:
        # plot a line from X[i] to X[j]
        # use some zip magic to make it happen:
        plt.plot(*zip(X[j], X[i]), color='black')
```

</details>

Pour la question 2, vous devriez obtenir un graphique ayant cet aspect

For question 2, you should get a graph that looks like this:

Le résultat de la question 7 est le suivant :

Ai-je inventé cet exercice corsé ? Pas du tout, il vient de l’ouvrage [*Python Data Science Handbook*](https://jakevdp.github.io/PythonDataScienceHandbook/02.08-sorting.html#Example:-k-Nearest-Neighbors). Mais, si je vous l’avais indiqué immédiatement, auriez-vous cherché à répondre aux questions ?

Par ailleurs, il ne serait pas une bonne idée de généraliser cet algorithme à de grosses données. La complexité de notre approche est $O(N^2)$. L’algorithme implémenté par `Scikit-Learn` est
en $O[NlogN]$.

De plus, le calcul de distances matricielles en utilisant la puissance des cartes graphiques serait plus rapide. A cet égard, la librairie [faiss](https://github.com/facebookresearch/faiss) ou les *frameworks* spécialisés dans le calcul de distance entre des vecteurs à haute dimension comme [ChromaDB](https://www.trychroma.com/)
offrent des performances beaucoup plus satisfaisantes que celles que permettraient `Numpy` sur ce problème précis.

# 6. Exercices supplémentaires

> **Comprendre le principe de l’algorithme <code>PageRank</code>**
>
> `Google` est devenu célèbre grâce à son algorithme `PageRank`. Celui-ci permet, à partir
> de liens entre sites *web*, de donner un score d’importance à un site *web* qui va
> être utilisé pour évaluer sa centralité dans un réseau. L’objectif de cet exercice est d’utiliser `Numpy` pour mettre en oeuvre un tel algorithme à partir d’une matrice d’adjacence qui relie les sites entre eux.
>
> 1.  Créer la matrice suivante avec `Numpy`. L’appeler `M`:
>
> $$
> \begin{bmatrix}
> 0 & 0 & 0 & 0 & 1 \\
> 0.5 & 0 & 0 & 0 & 0 \\
> 0.5 & 0 & 0 & 0 & 0 \\
> 0 & 1 & 0.5 & 0 & 0 \\
> 0 & 0 & 0.5 & 1 & 0
> \end{bmatrix}
> $$
>
> 1.  Pour représenter visuellement ce *web* minimaliste,
>     convertir en objet `networkx` (une librairie spécialisée
>     dans l’analyse de réseau) et utiliser la fonction `draw`
>     de ce package.
>
> Il s’agit de la transposée de la matrice d’adjacence
> qui permet de relier les sites entre eux. Par exemple,
> le site 1 (première colonne) est référencé par
> les sites 2 et 3. Celui-ci ne référence que le site 5.
>
> 1.  A partir de la page wikipedia anglaise de `PageRank`, tester
>     sur votre matrice.

Le site 1 est assez central car il est référencé 2 fois. Le site
5 est lui également central puisqu’il est référencé par le site 1.